dashevo/js-grpc-common

.travis.yml
scripts/travis-deploy.sh

Also use latest dist "bionic" and bump LTS to 12 in deploy script.

chore: Update Travis Node versions

---

index.js
lib/server/error/DeadlineExceededGrpcError.js
lib/server/error/GrpcError.js
lib/server/error/NotFoundGrpcError.js
lib/server/error/ResourceExhaustedGrpcError.js
package-lock.json
package.json
test/unit/server/error/InvalidArgumentGrpcError.spec.js

- NotFoundGrpcError
- DeadlineExceededGrpcError
- ResourceExhaustedGrpcError

feat: add additional gRPC errors

---

lib/server/error/GrpcError.js
lib/server/error/VerboseInternalGrpcError.js
lib/server/error/wrapInErrorHandlerFactory.js
test/unit/server/error/FailedPreconditionGrpcError.spec.js
test/unit/server/error/GrpcError.spec.js
test/unit/server/error/InvalidArgumentGrpcError.spec.js
test/unit/server/error/wrapInErrorHandlerFactory.spec.js

We need better error reporting to make the debug process easier
Debug mode was added to respond internal error with message and stack
Unit tests
No
- [] I have assigned this pull request to a milestone

feat: debug mode to respond internal error with message and stack

---

package-lock.json
package.json

Version bumped to 0.3.1
Unit tests
No

chore: bump version to 0.3.1

---

lib/server/error/VerboseInternalGrpcError.js
test/unit/server/error/VerboseInternalGrpcError.spec.js

Add a condition to the `VerboseInternalGrpcError` that attaches full trace if the last line of it can't be extracted
Wrote a new test for the specific case
None

fix: TypeError: Cannot read property 'trim' of undefined

---

index.js
lib/server/error/AlreadyExistsGrpcError.js

We need to throw already exists errors instead of invalid argument in DAPI
- Added already exists error class
Nope
Nope

feat: add already exists error

---

lib/client/interceptors/jsonToProtobufInterceptorFactory.js
lib/client/interceptors/protocolVersionInterceptorFactory.js
lib/convertObjectToMetadata.js
lib/loadPackageDefinition.js
lib/server/checks/checkVersionWrapperFactory.js
lib/server/createServer.js
package-lock.json
package.json
test/integration/convertObjectToMetadata.spec.js
test/unit/client/converters/jsonToProtobufFactory.spec.js

The deprecated `grpc` dependency needed updating to `@grpc/grpc-js` for future support and to speed up builds in CI.
- Remove obsolete `grpc`
- Remove unsupported `grpc-health-check`
- Add `@grpc/grpc-js`
- Update and dedupe deps
- Fix broken test
- With `npm run test`
- In CI
None

chore: update grpc

---

package-lock.json
package.json

Version bumped to 0.3.6
Unit tests
None

chore: bump version to 0.3.6

---

lib/client/interceptors/jsonToProtobufInterceptorFactory.js
lib/client/interceptors/protocolVersionInterceptorFactory.js
lib/convertObjectToMetadata.js
lib/loadPackageDefinition.js
lib/server/checks/checkVersionWrapperFactory.js
lib/server/createServer.js
package-lock.json
package.json
test/integration/convertObjectToMetadata.spec.js

`js-grpc-common` was released with a breaking change but only a patch version increase, causing platform to fail.
Revert grpc changes to re-release another patch version.
In CI
None (relative to previous 0.3.x release series)

chore: revert to grpc to fix npm release version

---

package-lock.json
package.json

0.3.6 was released as a patch when it should have been a minor version, so 0.3.7 now needs releasing with the old code again
Bump version to 0.3.7
In CI
None

chore: bump version to 0.3.7

---

lib/client/interceptors/jsonToProtobufInterceptorFactory.js
lib/client/interceptors/protocolVersionInterceptorFactory.js
lib/convertObjectToMetadata.js
lib/loadPackageDefinition.js
lib/server/checks/checkVersionWrapperFactory.js
lib/server/createServer.js
package-lock.json
package.json
test/integration/convertObjectToMetadata.spec.js

The deprecated `grpc` dependency needed updating to `@grpc/grpc-js` for future support and to speed up builds in CI.
- Remove obsolete `grpc`
- Remove unsupported `grpc-health-check`
- Add `@grpc/grpc-js`
- Update and dedupe deps
- Fix broken test
- With `npm run test`
- In CI
None

chore: update to grpc-js

---

package-lock.json
package.json

Bump version to 0.4.0
In CI
None

chore: bump version to 0.4.0

---

lib/server/error/FailedPreconditionGrpcError.js
test/unit/server/error/FailedPreconditionGrpcError.spec.js

Failed precondition error has a redundant prefix.
- Removed the prefix
With tests
None

feat: remove failed precondition error prefix

---

.github/workflows/test_and_release.yml
package-lock.json

We need to update to node 16
- Update package to node 16
- Run tests
- Update CI
In CI
None

chore: update to node 16

---

package-lock.json

We need to update to node 16
- Update package to node 16
In CI
None

chore: update package lock for node 16

---

package-lock.json
package.json

Bump version for release
Bump version to 0.5.1

chore: bump version to 0.5.1

---

package-lock.json
package.json

Release was failing with `git@github.com: Permission denied (publickey).`
Force use of HTTPS to pull from external github repos
In CI
None

chore: fix git errors in ci

---

package-lock.json
package.json

Bump version for release
Bump version to 0.5.2

chore: bump version to 0.5.2

---

package-lock.json
package.json

Release was failing with `git@github.com: Permission denied (publickey).`
Force use of HTTPS to pull from external github repos
In CI
None

chore: fix npm automatic replacement to +ssh

---

package-lock.json
package.json

Bump version for release
Bump version to 0.5.3

chore: bump version to 0.5.3

---

package-lock.json
package.json

Bump version for release
Bump version to 0.5.4

chore: bump version to 0.5.4
